import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://dlcdnwebimgs.asus.com/gain/8442632c-11ac-4a3a-8c17-66999eeeef36/w800",
    title: "ASUS Vivobook S 15",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Asus",
    color: "Gray",
    category: "laptop",
  },
  {
    img: "https://dlcdnwebimgs.asus.com/gain/e1c062dc-b3ad-4b84-b310-eda9f5984d2c/w185/fwebp",
    title: "ASUS Zenbook DUO (2024) UX840",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Asus",
    color: "black",
    category: "laptop",
  },

  {
    img: "https://dlcdnwebimgs.asus.com/gain/47011AB5-5DAE-4098-B2F4-D310A828E3E2/w717/h525/w273",
    title: "ROG Strix G16 (2024)",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Asus",
    color: "black",
    category: "laptop",
  },
  {
    img: "https://dlcdnwebimgs.asus.com/gain/6d0f971b-66ab-4371-83a7-3856cec08d62/w185/fwebp",
    title: "NASUS Zenbook 14 Flip OLED (UP3404",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Asus",
    color: "Gray",
    category: "laptop",
  },
  {
    img: "https://appleasia.lk/wp-content/uploads/2024/09/midnight1-768x768.jpg",
    title: "Macbook Air M3 2024",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Apple",
    color: "blue",
    category: "laptop",
  },
  {
    img: "https://appleasia.lk/wp-content/uploads/2024/09/website-photo-size-6-768x768.webp",
    title: "MacBook Pro M3",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Apple",
    color: "black",
    category: "laptop",
  },

  {
    img: "https://appleasia.lk/wp-content/uploads/2024/09/iPad-10th-Gen-blue-768x768.jpg",
    title: "iPad ( 10th Gen )",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Apple",
    color: "blue",
    category: "tablet",
  },

  {
    img: "https://appleasia.lk/wp-content/uploads/2024/09/iPad-Pro-M1-Spacegrey-11-ich-2-1-768x768.jpg",
    title: "iPad Pro M1",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Apple",
    color: "Gray",
    category: "tablet",
  },

  {
    img: "https://appleasia.lk/wp-content/uploads/2024/09/Apple-watch-ultra-2-Orange-trail-loop-band-1-scaled-1-768x768.webp",
    title: "Apple Watch Ultra 2 Trail Loop Band",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Apple",
    color: "Gray",
    category: "watch",
  },

  {
    img: "https://appleasia.lk/wp-content/uploads/2024/09/Apple-watch-ultra-2-blue-ocean-band-1-scaled-1-768x768.webp",
    title: "Apple Watch Ultra 2 Ocean Band",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Apple",
    color: "blue",
    category: "watch",
  },
  {
    img: "https://appleasia.lk/wp-content/uploads/2024/09/iphone-16-TEAL1-768x768.jpg",
    title: "iPhone 16 Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Apple",
    color: "green",
    category: "phone",
  },
  {
    img: "https://appleasia.lk/wp-content/uploads/2024/09/iPhone-15-Plus-All-Colours-%EF%A3%BF-10-768x768.jpg",
    title: "iPhone 15 Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Apple",
    color: "black",
    category: "phone",
  },
  {
    img: "https://images.samsung.com/is/image/samsung/assets/us/2407/smartphones/smartphones-updates-scomb6q6-430/MobilePCD_NV06_Discover-3_B6-pc.jpg?$140_140_JPG$",
    title: "Galaxy Z Flip6",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Samsung",
    color: "blue",
    category: "phone",
  },
  {
    img: "https://image-us.samsung.com/us/smartphones/galaxy-s24/all-gallery/01_E2_OnlineExclusive_JadeGreen_Lockup_1600x1200.jpg?$product-card-small-jpg$",
    title: "Galaxy S24+",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Samsung",
    color: "green",
    category: "phone",
  },

  {
    img: "https://image-us.samsung.com/us/smartphones/galaxy-s24/all-gallery/01_E3_TitaniumBlack_Lockup_1600x1200.jpg?$product-card-small-jpg$",
    title: "Galaxy S24 Ultra",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Samsung",
    color: "black",
    category: "phone",
  },
  {
    img: "https://celltronics.lk/wp-content/uploads/2024/02/Samsung-Galaxy-Tab-S9-FE-Plus-5G-1-768x768.jpg",
    title: "Samsung Galaxy Tab S9",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Samsung",
    color: "black",
    category: "tablet",
  },
  {
    img: "https://celltronics.lk/wp-content/uploads/2023/11/Samsung_Galaxy_Tab_A9_4GB_RAM_64GB-removebg-preview.png",
    title: "Samsung Galaxy Tab A9",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Samsung",
    color: "blue",
    category: "tablet",
  },
  // {
  //   img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
  //   title: "Vans Unisex Low-Top",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "100",
  //   company: "Vans",
  //   color: "blue",
  //   category: "sandals",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
  //   title: "Classic Bandana Sneakers",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Nike",
  //   color: "black",
  //   category: "sandals",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
  //   title: "Chunky High Heel",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Vans",
  //   color: "black",
  //   category: "heels",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
  //   title: "Slip On Stiletto High Heel",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "100",
  //   company: "puma",
  //   color: "black",
  //   category: "heels",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
  //   title: "DREAM PAIRS Court Shoes",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "150",
  //   company: "Nike",
  //   color: "red",
  //   category: "heels",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
  //   title: "Nike Air Vapormax Plus",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "200",
  //   company: "Nike",
  //   color: "red",
  //   category: "sneakers",
  // },

  // {
  //   img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
  //   title: "Low Mid Block Heels",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "200",
  //   company: "Nike",
  //   color: "black",
  //   category: "heels",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
  //   title: "Chunky High Heel",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Adidas",
  //   color: "black",
  //   category: "heels",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
  //   title: "Amore Fashion Stilettos",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "150",
  //   company: "Adidas",
  //   color: "white",
  //   category: "heels",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
  //   title: "Bridal Sandals Glitter",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Adidas",
  //   color: "black",
  //   category: "heels",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
  //   title: "Wedding Prom Bridal",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Adidas",
  //   color: "black",
  //   category: "flats",
  // },
];

export default data;
